#!/bin/bash

case $1 in
    cinnamon)
        xbindkeys
        sh ~/.fehbg &
        exec cinnamon-session
        ;;
    i3)
        xbindkeys
        sh ~/.fehbg &
        exec i3
        ;;
    *)
        xbindkeys
        exec $1
        ;;
esac
