#!/bin/bash

case $1 in
    Cinnamon)
        xbindkeys
        setxkbmap -option caps:escape
        exec cinnamon-session
        ;;
    i3)
        xbindkeys
        setxkbmap -option caps:escape
        sh ~/.fehbg &
        exec i3
        ;;
    *)
        xbindkeys
        exec $1
        ;;
esac
