version = 3
final_space = true
console_title_template = "Terminal"

[palette]
background = "#002b36"
foreground = "#d5d5d5"
blue = "#61AFEF"
green = "#98c379"
cyan = "#56B6C2"
path = "#2C3E50"
time_bg = "#3B4252"
git_clean = "#A3BE8C"
git_dirty = "#D08770"

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:green"
    template = "\u256D "

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:blue"
    template = " \uE5FF {{ .Path }} "

[[blocks]]
  type = "prompt"
  alignment = "right"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:green"
    foreground_templates = [ "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}", "{{ if gt .Ahead 0 }}#B388FF{{ end }}", "{{ if gt .Behind 0 }}#B388FB{{ end }}" ]
    template = "{{ .HEAD }} {{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
    [blocks.segments.options]
    fetch_status = true
    fetch_upstream_icon = false
    source = "cli"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:green"
    template = "\u2570 "

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = ['{{ if gt .Code 0 }}#EE0066{{ end }}', '{{ if eq .Code 0 }}green{{ end }}']
    foreground = "p:green"
    template = "{{ if gt .Code 0 }}{{ .Code }} > {{ end }}{{ if eq .Code 0 }}> {{ end }}"

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
  alignment = "right"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "#E5C07B"
    template = " {{ .FormattedMs }} "

    [blocks.segments.options]
      threshold = 500
      style = "austin"
      always_enabled = true
