#!/bin/bash

main() {
        local registry
        local action="$1"
        local path="$2"
        if [[ -z $DOCKER_QUERY_REGISTRY ]]; then
                echo "Docker Registry not set."
                echo "You can set the registry by doing (to skip this warning next time):"
                echo "export DOCKER_QUERY_REGISTRY=https://registry.your-host.tld/"
                echo
                echo "Please enter your registry and press [ENTER]:"
                read registry
        else
                registry="$DOCKER_QUERY_REGISTRY"
        fi
        if [[ $action == "list" ]] || [[ $action == "ls" ]]; then
                curl -s "$registry/v2/_catalog"
        fi
        if [[ $action == "tags" ]] || [[ $action == "get-tags" ]]; then
                curl -s "$registry/v2/$path/tags/list"
        fi
        if [[ $action == "tag" ]] || [[ $action == "get-tag" ]]; then
                curl -s "$registry/v2/$path/manifests/$3"
        fi
        if [[ $action == "tag-date" ]] || [[ $action == "get-tag-date" ]] ||
                [[ $action == "tag-dates" ]] || [[ $action == "get-tag-dates" ]]; then
                curl -s "$registry/v2/$path/manifests/$3" | jq -r .history[].v1Compatibility | jq -r .created | sort
        fi
}

main "$@"
