#!/usr/bin/env bash

splash() {
        echo "SSH-Gorilla"
        echo "Best SSH-Management for Gorillas!"
        echo "Bananas already included!"
        echo
        echo
}

title() {
        echo "$1"
        echo "==============================================================================="
        echo
}

main() {
        splash
        local action
        local group
        local result
        action="$1"
        unset DISPLAY
                if [[ "$action" == "l" ]] || \
                        [[ "$action" == "ls" ]] || \
                        [[ "$action" == "list" ]]; then
                        title "Loaded Keys (short)"
                        ssh-add -l
                fi
                if [[ "$action" == "L" ]]; then
                        title "Loaded Keys (full)"
                        ssh-add -L
                fi
                if [[ "$action" == "a" ]] || \
                        [[ "$action" == "add" ]]; then
                        local key
                        group="$2"
                        title "Loading keys of $group"
                        result=$(jq -r ".groups[] | select(.name==\"$group\")" \
                                < "$HOME/.sshg.json")
                        echo "$result" | jq -rc '.keys[]' | while read -r key; do
                                ssh-add "$key"
                        done
                fi
                if [[ "$action" == "avail" ]]; then
                        local key
                        title "Listing all available groups and keys"
                        result=$(jq ".groups[]" \
                                < "$HOME/.sshg.json")
                        echo "$result"
                fi
                if [[ "$action" == "d" ]] || \
                        [[ "$action" == "del" ]] || \
                        [[ "$action" == "delete" ]] || \
                        [[ "$action" == "rm" ]]; then
                        local key
                        group="$2"
                        title "Removing keys of $group"
                        result=$(jq -r ".groups[] | select(.name==\"$group\")" \
                                < "$HOME/.sshg.json")
                        echo "$result" | jq -rc '.keys[]' | while read -r key; do
                                ssh-add -d "$key"
                        done
                fi
                if [[ "$action" == "D" ]]; then
                        title "Removing all keys"
                        ssh-add -D
                fi
}

main "$@"
