---
version: 2
sync:
    enabled: true
    rclone_engine: embedded
    endpoints:
        - id: google-drive
          type: rclone
          rclone_remote: gdrive
          provider: google-drive
          path: syncsh
          enabled: true
suggest:
    enabled: true
    menu: true
    completions: true
    menu_max: 12
    accept:
        - Right
