# yaml-language-server: $schema=https://remnix.app/config.schema.json
---
version: 2
sync:
  enabled: true
  rclone_engine: embedded
  endpoints:
    - id: gdrive
      type: rclone
      name: gdrive
      enabled: true
      rclone_remote: gdrive
      provider: custom
      path: remnix
suggest:
  enabled: true
  menu: true
  menu_max: 12
  completions: true
  accept:
    - Right
pty_proxy:
  enabled: true
  height: 40
