"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Marco Kellershoff"
email = "marco@mistweaverco.com"

[signing]
behavior = "own"
backend = "gpg"
backends.gpg.program = "gpg2"

[aliases]
slog = ["util", "exec", "--", "sh", "-c", "jj st && echo --- && jj log -n 5"]
p = ["git", "push"]
re = ["rebase"]

[ui]
default-command = "slog"
paginate = "never"

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
  "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
  "-c", "DiffConflictsWithHistory", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true
