"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Marco Kellershoff"
email = "marco.kellershoff@tbint.de"

[signing]
behavior = "own"
backend = "gpg"
backends.gpg.program = "gpg2"

[aliases]
slog = ["util", "exec", "--", "sh", "-c", "jj st && echo --- && jj log -n 5"]
p = ["git", "push"]
re = ["rebase"]

[ui]
default-command = "slog"
paginate = "never"
