theme = "sunset"

[buffer.chathistory]
infinite_scroll = true

[buffer.commands]
show_description = true

[buffer.timestamp]
format = "%Y-%m-%d %H:%M:%S"

[actions.buffer]
click_channel_name = "replace-pane"
click_highlight = "replace-pane"
click_username = "replace-pane"

[actions.sidebar]
buffer = "replace-pane"

[servers.liberachat]
should_ghost = true
ghost_sequence = ["REGAIN"]
nickname = "GorillaMoe"
username = "GorillaMoe"
server = "irc.libera.chat"
channels = [
  "#mistweaverco",
  "#technicalrenaissance"
]
nick_password_file_first_line_only = true
nick_password_file = "~/.config/halloy/passwords/liberachat"

[servers.liberachat.sasl.plain]
username = "GorillaMoe"
password_file_first_line_only = true
password_file = "~/.config/halloy/passwords/liberachat"

[buffer.channel.topic]
enabled = true
